modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"
[[mods]]
modId="wotw"
#Version of the mod
version="1.0.0"
displayName="Winds of the Western"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
logoFile="logo.png" #optional
credits="Credits to YeoXuHang who is also in Author!" #optional
authors="Heizer, YeoXuHang"
description='''
This Mod brings a lot of stuff from the Wild Western into the Game. Including Blocks, Items Entities and more, there are things for everyone!
'''
[[dependencies.wotw]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.wotw]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
